# Capstone 2: Business Analysis with Python 

## Sales Territorry Analysis 

This project analyzes sales performance across assigned sales territories using Python, Pandas, and Matplotlib.

The analysis includes:
- Monthly revenue trends
- Store performance rankings
- Customer purchasing analysis
- Product category analysis
- Marketing recommendations

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Store Detail Data

In [5]:
store_detail = pd.read_csv('StoreDetail.csv')

In [6]:
store_detail.head()

  Store Location     State  Store ID Territory Manager Region  Region Director
0         Aurora  Colorado       701          Jim Heck   West  Cassie Chambers
1       Berthoud  Colorado       702          Jim Heck   West  Cassie Chambers
2        Boulder  Colorado       703          Jim Heck   West  Cassie Chambers
3    Castle Rock  Colorado       704          Jim Heck   West  Cassie Chambers
4         Denver  Colorado       705          Jim Heck   West  Cassie Chambers

In [7]:
store_detail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Store Location     111 non-null    object
 1   State              111 non-null    object
 2   Store ID           111 non-null    int64
 3   Territory Manager  111 non-null    object
 4   Region             111 non-null    object
 5   Region Director    111 non-null    object
dtypes: int64(1), object(5)
memory usage: 5.3+ KB

## Customer List Data

In [8]:
customer_list = pd.read_csv('Customer_list.csv')

In [9]:
customer_list.head()

     cust_id|date|time|name|email|phone|sms-opt-out
0  1|2023-03-15|08:45:12|Rachel|rachel@centralper...
1  2|2023-05-22|12:30:45|R. Geller|rossg@centralp...
2  3|2023-07-09|18:15:27|Monica Geller|chefmonica...
3  4|2023-09-01|21:05:33|Chandler Bing|chandlerb@...
4  5|2023-11-18|14:22:10|Joey|howyoudoing@central...

In [10]:
customer_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 1 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   cust_id|date|time|name|email|phone|sms-opt-out   521 non-null    object
dtypes: object(1)
memory usage: 4.2+ KB

## Products Data

In [11]:
products = pd.read_csv('Products.csv')

In [12]:
products.head()

    Prod Num                        Product  CategoryID SubcategoryID
0  105248-IT               TCL NXTPAPER 10s         120       120-tab
1  105249-IT  Dell Latitude 7320 Detachable         120       120-tab
2  105250-IT                     Realme Pad         120       120-tab
3  105251-IT             Lenovo Tab P12 Pro         120       120-tab
4  105252-IT        Microsoft Surface Pro 9         120       120-tab

In [13]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 669 entries, 0 to 668
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Prod Num       669 non-null    object
 1   Product        669 non-null    object
 2   CategoryID     669 non-null    int64
 3   SubcategoryID  669 non-null    object
dtypes: int64(1), object(3)
memory usage: 21.0+ KB

## Product Categories Data

In [14]:
product_categories = pd.read_csv('ProductCategories.csv')

In [15]:
product_categories.head()

   CategoryID                  Category SubcategoryID           Subcategory
0         120  Technology & Accessories       120-tab               Tablets
1         120  Technology & Accessories       120-cal           Calculators
2         120  Technology & Accessories       120-sof     Software Download
3         120  Technology & Accessories       120-hea            Headphones
4         120  Technology & Accessories       120-ext  External Accessories

In [16]:
product_categories.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CategoryID     52 non-null     int64
 1   Category       52 non-null     object
 2   SubcategoryID  52 non-null     object
 3   Subcategory    52 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.8+ KB

## Store Sales Data

In [17]:
store_sales = pd.read_csv('StoreSales.csv')

In [18]:
store_sales.head()

  Transaction Date  Store ID  RewardsID  Prod Num  Sale Amount
0         1/1/2022       702        NaN  105349-M         8.00
1         1/1/2022       704        NaN  105350-T       144.00
2         1/1/2022       705        NaN  105351-M        44.00
3         1/1/2022       705        NaN  105352-M        47.61
4         1/1/2022       705        NaN  105353-A        20.36

In [19]:
store_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335129 entries, 0 to 335128
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction Date  335129 non-null  object
 1   Store ID          335129 non-null  int64
 2   RewardsID         34943 non-null   float64
 3   Prod Num          335129 non-null  object
 4   Sale Amount       335129 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 12.8+ MB

# Core Marketing Analysis

## Question 1: Territory Managers and Store Locations
The assigned sales territory is located in the Northeast region. 

The assigned territories include:
- Maryland
- Massachusetts

This analysis will focus on stores located within these territories to evaluate sales performance, customer activity, product category trends, and future marketing opportunities.

In [20]:
northeast_territory = store_detail[
    store_detail['State'].isin(['Maryland', 'Massachusetts'])
    ]

northeast_territory

,Store Location,State,Store ID,Territory Manager,Region,Region Director
43,Annapolis,Maryland,731,Shruti Reddy,Northeast,Michael Jarvis
44,Back River,Maryland,732,Shruti Reddy,Northeast,Michael Jarvis
45,Baltimore,Maryland,733,Shruti Reddy,Northeast,Michael Jarvis
46,Germantown,Maryland,734,Shruti Reddy,Northeast,Michael Jarvis
47,Howard,Maryland,735,Shruti Reddy,Northeast,Michael Jarvis
48,North Harford,Maryland,736,Shruti Reddy,Northeast,Michael Jarvis
49,Parkville,Maryland,737,Shruti Reddy,Northeast,Michael Jarvis
50,Queen Anne's County,Maryland,738,Shruti Reddy,Northeast,Michael Jarvis
51,Ridgely,Maryland,739,Shruti Reddy,Northeast,Michael Jarvis
52,Boston,Massachusetts,730,Bo Heap,Northeast,Michael Jarvis
53,Attleboro,Massachusetts,801,Bo Heap,Northeast,Michael Jarvis
54,Falmouth,Massachusetts,802,Bo Heap,Northeast,Michael Jarvis
55,Framingham,Massachusetts,803,Bo Heap,Northeast,Michael Jarvis
56,Haverhill,Massachusetts,804,Bo Heap,Northeast,Michael Jarvis
57,Hingham,Massachusetts,805,Bo Heap,Northeast,Michael Jarvis
58,Holyoke,Massachusetts,806,Bo Heap,Northeast,Michael Jarvis
59,Leominster,Massachusetts,807,Bo Heap,Northeast,Michael Jarvis
60,Lowell,Massachusetts,808,Bo Heap,Northeast,Michael Jarvis
61,Lynn,Massachusetts,809,Bo Heap,Northeast,Michael Jarvis
62,Nantucket,Massachusetts,810,Bo Heap,Northeast,Michael Jarvis
63,New Bedford,Massachusetts,811,Bo Heap,Northeast,Michael Jarvis
64,Northampton,Massachusetts,812,Bo Heap,Northeast,Michael Jarvis
65,Pittsfield,Massachusetts,813,Bo Heap,Northeast,Michael Jarvis
66,Provincetown,Massachusetts,814,Bo Heap,Northeast,Michael Jarvis
67,Quincy,Massachusetts,815,Bo Heap,Northeast,Michael Jarvis
68,Somerville,Massachusetts,816,Bo Heap,Northeast,Michael Jarvis
69,Worcester,Massachusetts,817,Bo Heap,Northeast,Michael Jarvis

## Question 2: Monthly Total Revenue
This section analyzes monthly in store sales revenue for stores located in Maryland and Massachusetts within the Northeast region.

In [32]:
monthly_revenue = territory_sales.groupby(
    ['State', 'Month']
)['Sale Amount'].sum().reset_index()

In [36]:
monthly_revenue_display = monthly_revenue.copy()

monthly_revenue_display['Sale Amount'] = monthly_revenue_display['Sale Amount'].map(
    '${:,.2f}'.format
)

In [37]:
monthly_revenue_display[
    monthly_revenue_display['State'] == 'Maryland'
    ]

       State    Month  Sale Amount
0   Maryland  2022-01  $190,064.90
1   Maryland  2022-02  $197,529.18
2   Maryland  2022-03  $210,228.48
3   Maryland  2022-04  $179,004.18
4   Maryland  2022-05  $212,028.70
5   Maryland  2022-06  $198,318.98
6   Maryland  2022-07  $231,208.13
7   Maryland  2022-08  $203,503.40
8   Maryland  2022-09  $158,952.74
9   Maryland  2022-10  $200,423.07
10  Maryland  2022-11  $202,365.13
11  Maryland  2022-12  $226,340.81
12  Maryland  2023-01  $247,207.80
13  Maryland  2023-02  $215,146.55
14  Maryland  2023-03  $212,397.10
15  Maryland  2023-04  $253,354.48
16  Maryland  2023-05  $236,271.38
17  Maryland  2023-06  $243,603.42
18  Maryland  2023-07  $218,664.85
19  Maryland  2023-08  $233,256.77
20  Maryland  2023-09  $227,638.37
21  Maryland  2023-10  $248,095.23
22  Maryland  2023-11  $242,019.94
23  Maryland  2023-12  $236,037.31
24  Maryland  2024-01  $234,650.29
25  Maryland  2024-02  $200,891.75
26  Maryland  2024-03  $263,664.98
27  Maryland  2024-04  $225,960.88
28  Maryland  2024-05  $248,901.48
29  Maryland  2024-06  $213,366.79
30  Maryland  2024-07  $233,256.77
31  Maryland  2024-08  $234,863.77
32  Maryland  2024-09  $240,869.83
33  Maryland  2024-10  $247,456.61
34  Maryland  2024-11  $230,600.64
35  Maryland  2024-12  $247,207.80
36  Maryland  2025-01  $277,874.74
37  Maryland  2025-02  $262,318.88
38  Maryland  2025-03  $293,722.84
39  Maryland  2025-04  $206,982.63
40  Maryland  2025-05  $225,774.67
41  Maryland  2025-06  $216,983.57
42  Maryland  2025-07  $310,327.16
43  Maryland  2025-08  $311,949.14
44  Maryland  2025-09  $304,304.79
45  Maryland  2025-10  $359,699.69
46  Maryland  2025-11  $304,194.50
47  Maryland  2025-12  $332,129.99

In [38]:
monthly_revenue_display[
    monthly_revenue_display['State'] == 'Massachusetts'
    ]

            State    Month  Sale Amount
48  Massachusetts  2022-01   $69,396.42
49  Massachusetts  2022-02   $65,616.00
50  Massachusetts  2022-03   $77,390.00
51  Massachusetts  2022-04   $81,333.60
52  Massachusetts  2022-05   $75,919.64
53  Massachusetts  2022-06   $81,227.82
54  Massachusetts  2022-07   $67,271.23
55  Massachusetts  2022-08   $73,543.48
56  Massachusetts  2022-09   $58,716.74
57  Massachusetts  2022-10   $72,514.81
58  Massachusetts  2022-11   $70,654.73
59  Massachusetts  2022-12   $70,025.64
60  Massachusetts  2023-01  $139,388.56
61  Massachusetts  2023-02  $104,454.67
62  Massachusetts  2023-03  $112,443.92
63  Massachusetts  2023-04  $109,369.00
64  Massachusetts  2023-05  $109,021.42
65  Massachusetts  2023-06  $101,710.16
66  Massachusetts  2023-07  $120,793.96
67  Massachusetts  2023-08  $126,212.14
68  Massachusetts  2023-09  $121,968.93
69  Massachusetts  2023-10  $113,824.37
70  Massachusetts  2023-11  $105,670.08
71  Massachusetts  2023-12  $101,641.22
72  Massachusetts  2024-01  $117,915.05
73  Massachusetts  2024-02  $103,968.70
74  Massachusetts  2024-03  $110,968.54
75  Massachusetts  2024-04  $107,421.88
76  Massachusetts  2024-05  $106,193.39
77  Massachusetts  2024-06  $116,310.73
78  Massachusetts  2024-07  $126,212.14
79  Massachusetts  2024-08  $123,926.20
80  Massachusetts  2024-09  $111,867.10
81  Massachusetts  2024-10  $110,582.18
82  Massachusetts  2024-11   $96,729.12
83  Massachusetts  2024-12  $139,388.56
84  Massachusetts  2025-01  $150,745.88
85  Massachusetts  2025-02  $140,234.24
86  Massachusetts  2025-03  $160,846.61
87  Massachusetts  2025-04  $156,773.91
88  Massachusetts  2025-05  $157,710.74
89  Massachusetts  2025-06  $170,305.34
90  Massachusetts  2025-07  $191,697.95
91  Massachusetts  2025-08  $174,867.46
92  Massachusetts  2025-09  $168,503.25
93  Massachusetts  2025-10  $277,382.19
94  Massachusetts  2025-11  $196,108.93
95  Massachusetts  2025-12  $186,487.64

## Question 3: Store Sales Performance Rankings
This section ranks store performance within the Maryland and Massachusetts territories based on total sales revenue.

In [45]:
store_performance = territory_sales.groupby(
    ['State', 'Store ID']
)['Sale Amount'].sum().reset_index

In [55]:
store_performance = store_performance.sort_values(
    by='Sale Amount',
    ascending=False
)

In [54]:
store_performance_display = store_performance.copy()

store_performance_display['Sale Amount'] = (
    store_performance_display['Sale Amount']
    .round(2)
    .apply(lambda x: f'${x:,.2f}')
)
store_performance_display

            State  Store ID    Sale Amount
5        Maryland       736  $8,708,119.00
26  Massachusetts       817    $602,183.44
3        Maryland       734    $584,675.92
16  Massachusetts       807    $338,009.10
19  Massachusetts       810    $335,547.81
23  Massachusetts       814    $328,860.51
21  Massachusetts       812    $322,039.24
15  Massachusetts       806    $320,516.53
6        Maryland       737    $320,441.24
4        Maryland       735    $319,394.58
8        Maryland       739    $318,511.04
25  Massachusetts       816    $312,873.59
2        Maryland       733    $310,099.90
13  Massachusetts       804    $305,762.60
1        Maryland       732    $303,433.61
18  Massachusetts       809    $302,049.65
22  Massachusetts       813    $301,281.50
7        Maryland       738    $298,074.49
20  Massachusetts       811    $295,443.42
9   Massachusetts       730    $295,201.29
10  Massachusetts       801    $290,883.71
14  Massachusetts       805    $289,633.52
0        Maryland       731    $288,865.31
24  Massachusetts       815    $279,646.07
11  Massachusetts       802    $276,965.55
12  Massachusetts       803    $269,375.91
17  Massachusetts       808    $266,982.83